#!/bin/bash
#
# Test Skills Script
#
# Provides instructions for testing both Tempest coverage skills
#

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "================================================"
echo "Test Tempest Coverage Skills"
echo "================================================"
echo ""

echo -e "${BLUE}This script will help you test both skills.${NC}"
echo ""

echo "Prerequisites:"
echo "  ✓ Claude Code installed"
echo "  ✓ Repository paths configured"
echo "  ✓ In the project directory: $PROJECT_ROOT"
echo ""

read -p "Press Enter to continue..."
echo ""

echo "================================================"
echo "Test 1: Analysis Skill"
echo "================================================"
echo ""

echo "The jira-coverage-analysis skill performs fast gap analysis."
echo ""
echo "To test it:"
echo ""
echo "  1. Start Claude Code:"
echo "     cd $PROJECT_ROOT"
echo "     claude"
echo ""
echo "  2. Run one of these commands:"
echo ""
echo -e "${GREEN}     With Jira ticket:${NC}"
echo "     /jira-coverage-analysis RHEL-12345"
echo ""
echo -e "${GREEN}     With manual requirements:${NC}"
echo "     /jira-coverage-analysis"
echo "     "
echo "     Service: Cinder"
echo "     Feature: Volume multi-attach RBAC"
echo ""
echo "  3. Expected output:"
echo "     - Analysis report (< 1 minute)"
echo "     - Coverage gaps identified"
echo "     - Effort estimation"
echo "     - Implementation recommendations"
echo "     - NO code generation"
echo ""

read -p "Press Enter to see Test 2..."
echo ""

echo "================================================"
echo "Test 2: Implementation Skill"
echo "================================================"
echo ""

echo "The implement-tempest-tests skill implements complete tests."
echo ""
echo "To test it:"
echo ""
echo "  1. In the same Claude session:"
echo ""
echo "  2. Run one of these commands:"
echo ""
echo -e "${GREEN}     From Jira ticket:${NC}"
echo "     /implement-tempest-tests RHEL-12345"
echo ""
echo -e "${GREEN}     From manual requirements:${NC}"
echo "     /implement-tempest-tests"
echo "     "
echo "     Service: Cinder"
echo "     Feature: Simple volume create test"
echo ""
echo "  3. Expected output (5-10 minutes):"
echo "     - Pattern discovery"
echo "     - Test implementation"
echo "     - Tox validation (pep8 + py3)"
echo "     - Git branch + commit"
echo "     - Mandatory final recap"
echo ""

read -p "Press Enter to see Test 3..."
echo ""

echo "================================================"
echo "Test 3: Two-Step Workflow"
echo "================================================"
echo ""

echo "Test the recommended workflow: Analyze then Implement."
echo ""
echo "  1. In Claude:"
echo ""
echo "     Step 1 - Analyze (fast):"
echo "     /jira-coverage-analysis RHEL-12345"
echo ""
echo "     (Review the analysis report)"
echo ""
echo "     Step 2 - Implement (after approval):"
echo "     /implement-tempest-tests RHEL-12345"
echo ""
echo "  2. Expected:"
echo "     - Fast analysis first"
echo "     - Review before implementing"
echo "     - Implementation uses analysis findings"
echo ""

echo "================================================"
echo "Validation Checklist"
echo "================================================"
echo ""

echo "After testing, verify:"
echo ""
echo "  Analysis Skill:"
echo "  [ ] Runs in < 1 minute"
echo "  [ ] Produces analysis report"
echo "  [ ] Identifies gaps with priority"
echo "  [ ] Provides effort estimates"
echo "  [ ] No code generation"
echo "  [ ] No git operations"
echo ""
echo "  Implementation Skill:"
echo "  [ ] Discovers patterns"
echo "  [ ] Implements tests"
echo "  [ ] Runs tox validation"
echo "  [ ] Creates git branch"
echo "  [ ] Creates commit"
echo "  [ ] Provides mandatory recap"
echo "  [ ] Shows exact file paths"
echo "  [ ] Does NOT auto-push"
echo ""

echo "================================================"
echo "Troubleshooting"
echo "================================================"
echo ""

echo "If skills not found:"
echo "  - Ensure you're in: $PROJECT_ROOT"
echo "  - Check skills exist:"
echo "    ls -la .claude/skills/jira-coverage-analysis/"
echo "    ls -la .claude/skills/implement-tempest-tests/"
echo ""

echo "If repository not found:"
echo "  - Run: bash scripts/setup/configure-repos.sh"
echo "  - Or edit: .claude/skills/tempest-coverage/config.json"
echo ""

echo "If tox fails:"
echo "  - Install tox: pip install tox"
echo "  - Check repository has tox.ini"
echo ""

echo -e "${GREEN}Ready to test! Start Claude and try the commands above.${NC}"
echo ""
